### ISSUE TITLE
Add remaining support for AsyncBufRead

### ISSUE THREAD

**Issue by fairingrey** [rustasync/async-compression#21]
The remaining encoders/decoders that are yet to be supported through `AsyncBufRead`:

- [ ] gzip
- [ ] brotli
- [ ] zstd

Help would be appreciated!

**Comment by yoshuawuyts** [comment]
This should probably be a wrapper around `AsyncRead` instead, right?

**Comment by fairingrey** [comment]
I suppose it could be, although I originally went off of @Nemo157's original design, which was that the associated reader for a given `AsyncBufRead` encoder/decoder would be a type of `AsyncBufRead`. Though I don't imagine it'd take too long to refactor this, I wonder what he thinks.

**Comment by Nemo157** [comment]
Adding `AsyncRead` support would be pretty trivial, just wrap the incoming `AsyncRead` into a `BufReader` so that it supports `AsyncBufRead`. Since the en/decoders operate on in-memory buffers you need a buffering reader.
