### ISSUE TITLE
`crate::stream::GzipDecoder` fails with "CRC computed does not match" error

### ISSUE THREAD

**Issue by tesaguri** [rustasync/async-compression#29]
```rust
use std::io;

use async_compression::stream::GzipDecoder;
use bytes::Bytes;
use flate2::bufread::GzDecoder;
use futures::*;

fn main() {
    let payload: &[u8] = include_bytes!("user_timeline.gz");

    io::copy(&mut GzDecoder::new(payload), &mut io::sink())
        .expect("flate2"); // OK (as expected)

    futures::executor::block_on({
        let input = stream::iter(payload.windows(1).map(|b| Ok(Bytes::from_static(b))));
        GzipDecoder::new(input).try_for_each(|_| future::ok(()))
    })
    .expect("async-compression (split)"); // OK (as expected)

    futures::executor::block_on({
        let input = stream::iter(Some(Ok(Bytes::from_static(payload))));
        GzipDecoder::new(input).try_for_each(|_| future::ok(()))
    })
    .expect("async-compression (single chunk)"); // ERROR (unexpected)
}
```

Test data: [`user_timeline.gz`](https://github.com/rustasync/async-compression/files/3567085/user_timeline.gz) (a response body from `https://api.twitter.com/1.1/statuses/user_timeline.json?count=4` with `Content-Encoding: gzip`)

The above code panics with the following message:

```
thread 'main' panicked at 'async-compression (single chunk): Custom { kind: InvalidData, error: "CRC computed does not match" }', src/libcore/result.rs:1084:5
```

**Comment by Nemo157** [comment]
Yep something is definitely going wrong, added a failing test case in https://github.com/rustasync/async-compression/commit/2856c758cfd6ea70bddc1bf1e4d485c2c0412017 (are you happy with this test data being committed to the repo? I can try and generate another test file instead).

I can take a look at what is failing tomorrow.

**Comment by tesaguri** [comment]
> are you happy with this test data being committed to the repo?

Yes, go ahead.

I hereby license the data (https://github.com/rustasync/async-compression/files/3567085/user_timeline.gz) under CC0 1.0 (https://creativecommons.org/publicdomain/zero/1.0/), just in case you are curious.

**Comment by Nemo157** [comment]
Thanks, I ended up going with a simpler test case once I understood what the issue was. I'll try to publish a new release tomorrow with the fix.
